
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 28 00:05:37 GMT-03:00 2009
//----------------------------------------------------

package lambdac.frontend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAR = 6;
  public static final int LEFT_PAR = 5;
  public static final int ATOM = 11;
  public static final int EOF = 0;
  public static final int LAMBDA = 2;
  public static final int POINT = 3;
  public static final int DECLARE_KW = 8;
  public static final int BODY_KW = 9;
  public static final int error = 1;
  public static final int COMMA = 4;
  public static final int IDENTIFIER = 10;
  public static final int IS = 7;
}

